name: Supabase Günlük Yedekleme

on:
  schedule:
    # Her gün Türkiye saati ile 00:00'da (UTC 21:00) çalışır
    - cron: '0 21 * * *'
  workflow_dispatch: # Manuel çalıştırmak için

jobs:
  backup:
    runs-on: ubuntu-latest
    # Node 24'e şimdiden geçmek için
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout Code
        # v3 yerine v4 (veya en güncel sürüm) kullanıyoruz
        uses: actions/checkout@v4

      - name: Install PostgreSQL Tools
        run: sudo apt-get install -y postgresql-client

      - name: Backup Database
        run: |
          export PGPASSWORD="${{ secrets.DB_PASSWORD }}"

          pg_dump -h ipv4.db.rlhhlbnaecljcegabwak.supabase.co \
                  -U postgres \
                  -p 5432 \
                  -d postgres \
                  --no-password > backup_$(date +%Y-%m-%d).sql

      - name: Upload to Google Drive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.GDRIVE_JSON_KEY }}
          filename: backup_$(date +%Y-%m-%d).sql
          folderId: ${{ secrets.GDRIVE_FOLDER_ID }}
          overwrite: "false"