name: Supabase Günlük Yedekleme

on:
  schedule:
    # Her gün Türkiye saati ile 00:00'da (UTC 21:00) çalışır
    - cron: '0 21 * * *'
  workflow_dispatch: # Manuel çalıştırmak için

jobs:
  backup:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install PostgreSQL Tools
        run: |
          # PostgreSQL resmi depo anahtarını ekle
          sudo apt-get update
          sudo apt-get install -y wget gnupg
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          
          # Depoyu ekle (Ubuntu 24.04 veya 22.04 uyumlu)
          echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" | sudo tee /etc/apt/sources.list.d/pgdg.list
          
          # Listeyi güncelle ve v17 istemcisini kur
          sudo apt-get update
          sudo apt-get install -y postgresql-client-17

      - name: Backup Database
        run: |
          export PGPASSWORD="${{ secrets.DB_PASSWORD }}"

          # Host: aws-1-... (Panelden aldığın adres)
          # Port: 5432
          # pg_dump sürümünü kontrol etmek istersen: pg_dump --version
          pg_dump -h aws-1-eu-central-1.pooler.supabase.com \
                  -U postgres.rlhhlbnaecljcegabwak \
                  -p 5432 \
                  -d postgres \
                  --no-password \
                  --no-owner \
                  --no-privileges > backup_file.sql

      - name: Upload to Google Drive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.GDRIVE_JSON_KEY }}
          filename: backup_file.sql
          folderId: ${{ secrets.GDRIVE_FOLDER_ID }}
          overwrite: "true"
