name: Build and Release
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build and Publish
        run: npm run build:win
        env:
          VITE_SUPABASE_URL: ${{ secrets.SUPABASE_PROJECT_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}